FROM ubuntu:xenial

RUN apt-get update -y
RUN apt-get install -y git
RUN apt-get install -y cmake
RUN apt-get install -y autoconf
RUN apt-get install -y libtbb-dev
# RUN apt-get install -y libhdf3-dev
RUN apt-get install -y libbz2-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y clang

WORKDIR /mnt/project
